name: win

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: relwithdebinfo

jobs:
  win:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - os: windows-2019
            compiler: msvc2019
            vcpkg_triplet: x64-windows
          - os: windows-2022
            compiler: msvc2022
            vcpkg_triplet: x64-windows            
          - os: windows-latest
            compiler: clang-cl
            flags: -T ClangCL
            vcpkg_triplet: x64-windows

    steps:
      - uses: actions/checkout@v4
      - uses: brinkqiang/get-cmake@v1
      - name: vcpkg build
        uses: brinkqiang/vcpkg-action@v1
        id: vcpkg
        with:
          pkgs: gtest
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          token: ${{ github.token }}
          github-binarycache: true

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}\build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}\build
        run: cmake -DCMAKE_TOOLCHAIN_FILE=..\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.config.vcpkg_triplet }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.config.flags}} ..

      - name: Build
        working-directory: ${{github.workspace}}\build
        shell: bash
        run: cmake --build . --config ${{env.BUILD_TYPE}}
        
      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -C relwithdebinfo --output-on-failure --output-junit report.xml

      - name: Status
        uses: brinkqiang/github-status-action@v2
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Set Status'
          description: 'Passed'
          state: 'success'
